version: "3.3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "bw_go"
      MYSQL_USER: "bw"
      MYSQL_PASSWORD: "bw"
      MYSQL_ROOT_PASSWORD: "bw"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
